vich_uploader:
    db_driver: orm

    mappings:
        textures:
            uri_prefix: /images/skin
            upload_destination: '%kernel.project_dir%/public/images/skin'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        article:
            uri_prefix: /images/article
            upload_destination: '%kernel.project_dir%/public/images/article'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        wiki_icon:
            uri_prefix: /images/wiki/icon
            upload_destination: '%kernel.project_dir%/public/images/wiki/icon'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        wiki_pages:
            uri_prefix: /images/wiki/pages
            upload_destination: '%kernel.project_dir%/public/images/wiki/pages'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer